language: objective-c
osx_image: xcode10
branches:
  only:
    - master
notifications:
  email: false
install:
  - brew install clang-format
script:
  - xcodebuild -workspace cpp_utils.xcworkspace -scheme cpp_utils_test_mac -configuration Debug OBJROOT=build -sdk macosx clean test
  - xcodebuild -workspace cpp_utils.xcworkspace -scheme cpp_utils_test_ios -configuration Debug OBJROOT=build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.0' clean test
