language: objective-c
osx_image: xcode11.3
branches:
  only:
    - master
notifications:
  email: false
install:
  - brew install clang-format
script:
  - xcodebuild -workspace cpp_utils_mac.xcworkspace -scheme cpp_utils_mac_tests -configuration Debug OBJROOT=build -sdk macosx clean test
  - xcodebuild -workspace cpp_utils_ios.xcworkspace -scheme cpp_utils_ios_tests -configuration Debug OBJROOT=build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.2.2' clean test
